"""Data models for IdeaAgent."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import uuid4


class ResearchType(str, Enum):
    """Type of research experiment."""
    DEEP_LEARNING = "deep-learning"
    MACHINE_LEARNING = "machine-learning"
    AGENT = "agent"


class TaskStatus(str, Enum):
    """Status of a task."""
    PENDING = "pending"
    PLANNING = "planning"
    WAITING_APPROVAL = "waiting_approval"
    APPROVED = "approved"
    REJECTED = "rejected"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    STOPPED = "stopped"


@dataclass
class Task:
    """Represents a research task."""
    research_type: ResearchType
    idea_description: str
    status: TaskStatus = TaskStatus.PENDING
    id: str = field(default_factory=lambda: str(uuid4()))
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)
    plan: Optional["ExperimentPlan"] = None
    execution_results: list["ExecutionResult"] = field(default_factory=list)
    error_message: Optional[str] = None
    loop_count: int = 0
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        """Convert task to dictionary for MongoDB storage."""
        return {
            "id": self.id,
            "research_type": self.research_type.value,
            "idea_description": self.idea_description,
            "status": self.status.value,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "plan": self.plan.to_dict() if self.plan else None,
            "execution_results": [r.to_dict() for r in self.execution_results],
            "error_message": self.error_message,
            "loop_count": self.loop_count,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Task":
        """Create Task from dictionary."""
        return cls(
            id=data["id"],
            research_type=ResearchType(data["research_type"]),
            idea_description=data["idea_description"],
            status=TaskStatus(data["status"]),
            created_at=datetime.fromisoformat(data["created_at"]),
            updated_at=datetime.fromisoformat(data["updated_at"]),
            plan=ExperimentPlan.from_dict(data["plan"]) if data.get("plan") else None,
            execution_results=[
                ExecutionResult.from_dict(r) for r in data.get("execution_results", [])
            ],
            error_message=data.get("error_message"),
            loop_count=data.get("loop_count", 0),
            metadata=data.get("metadata", {}),
        )


@dataclass
class ExperimentStep:
    """Represents a step in an experiment plan."""
    step_number: int
    description: str
    skill_required: Optional[str] = None
    estimated_duration: Optional[int] = None  # in minutes
    status: str = "pending"  # pending, running, completed, failed, skipped

    def to_dict(self) -> dict:
        return {
            "step_number": self.step_number,
            "description": self.description,
            "skill_required": self.skill_required,
            "estimated_duration": self.estimated_duration,
            "status": self.status,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ExperimentStep":
        return cls(
            step_number=data["step_number"],
            description=data["description"],
            skill_required=data.get("skill_required"),
            estimated_duration=data.get("estimated_duration"),
            status=data.get("status", "pending"),
        )


@dataclass
class ExperimentPlan:
    """Represents an experiment plan generated by the LLM."""
    title: str
    description: str
    steps: list[ExperimentStep]
    estimated_total_time: Optional[int] = None
    skills_needed: list[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> dict:
        return {
            "title": self.title,
            "description": self.description,
            "steps": [s.to_dict() for s in self.steps],
            "estimated_total_time": self.estimated_total_time,
            "skills_needed": self.skills_needed,
            "created_at": self.created_at.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ExperimentPlan":
        return cls(
            title=data["title"],
            description=data["description"],
            steps=[ExperimentStep.from_dict(s) for s in data["steps"]],
            estimated_total_time=data.get("estimated_total_time"),
            skills_needed=data.get("skills_needed", []),
            created_at=datetime.fromisoformat(data["created_at"]),
        )


@dataclass
class ExecutionResult:
    """Represents the result of executing a step."""
    step_number: int
    success: bool
    output: str
    error: Optional[str] = None
    execution_time: float = 0.0  # in seconds
    artifacts: list[str] = field(default_factory=list)  # paths to generated files
    timestamp: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> dict:
        return {
            "step_number": self.step_number,
            "success": self.success,
            "output": self.output,
            "error": self.error,
            "execution_time": self.execution_time,
            "artifacts": self.artifacts,
            "timestamp": self.timestamp.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ExecutionResult":
        return cls(
            step_number=data["step_number"],
            success=data["success"],
            output=data["output"],
            error=data.get("error"),
            execution_time=data.get("execution_time", 0.0),
            artifacts=data.get("artifacts", []),
            timestamp=datetime.fromisoformat(data["timestamp"]),
        )
